/*
 * /*Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template*/
 


/**
 * @date : 20/1/2022
 * @author Teng Ting Li
 */
import java.awt.Color;
import java.awt.Graphics;
public class for_loop extends javax.swing.JFrame {

    /**
     * Creates new form for_loop
     */
    public for_loop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_graph = new javax.swing.JPanel();
        button_gt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_a1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_f1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_a2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_f2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_operation = new javax.swing.JComboBox<>();
        button_g2t = new javax.swing.JButton();
        button_g1t = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        panel_graph.setBackground(new java.awt.Color(255, 255, 255));
        panel_graph.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_graphLayout = new javax.swing.GroupLayout(panel_graph);
        panel_graph.setLayout(panel_graphLayout);
        panel_graphLayout.setHorizontalGroup(
            panel_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        panel_graphLayout.setVerticalGroup(
            panel_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        button_gt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_gt.setText("<html>\nPlot g(t)\n</html>");
        button_gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GUI FOR LOOP");

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 102, 102));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel2.setText("<html>\n\ng<sub>1</sub>(t) =\n\n\n</html>");

        tf_a1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        tf_a1.setText("5.0");

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel3.setText("<html>\n\nsin( 2&pi;\n\n\n</html>");

        tf_f1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        tf_f1.setText("5.0");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel4.setText("<html>\n\n t)\n\n\n</html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel5.setText("<html>  g<sub>2</sub>(t) =   </html>");

        tf_a2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        tf_a2.setText("2.0");

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel6.setText("<html>\n\nsin( 2&pi\n\n</html>");

        tf_f2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        tf_f2.setText("4.5");

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel7.setText("<html>\n\n t)\n\n\n</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cb_operation.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        cb_operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));

        button_g2t.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_g2t.setText("<html> Plot g<sub>2</sub>(t) </html>");
        button_g2t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_g2tActionPerformed(evt);
            }
        });

        button_g1t.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_g1t.setText("<html> Plot g<sub>1</sub>(t) </html>");
        button_g1t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_g1tActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel_graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(button_g1t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(button_gt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_g2t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(97, 97, 97))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cb_operation, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_g1t)
                        .addComponent(button_gt))
                    .addComponent(button_g2t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel_graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //global variable that i declear myself
    Graphics drawer;
    double y_max; 
    double y_max_1st, y_min_1st, x_max_1st, x_min_1st;
    int w, h;
    int plot_x_previous, plot_y_previous;
    
    public void graph_initialize(){     //draw everything to the graph
        //set initial value -> draw axis line -> draw axis scale
        drawer = panel_graph.getGraphics();
        drawer.setColor(Color.white);
        w = panel_graph.getWidth();
        h = panel_graph.getHeight();
        y_max_1st = y_min_1st = x_max_1st = x_min_1st = 0;
        plot_x_previous = 10;
        plot_y_previous = h/2;
        drawer.fillRect(0, 0, w, h);
        drawer.setColor(Color.black);
        drawer.drawLine(0, h/2, w, h/2);    //draw x-axis 
        drawer.drawLine(10, 0, 10, h);         //draw y-axis
        //draw y scale according to value of y_max
        drawer.drawString(String.valueOf(y_max), 15, 10);
        drawer.drawString(String.valueOf(-y_max), 15, h - 10);
        drawer.drawString(String.valueOf(y_max / 2), 15, (int)((h / 4) + 5));
        drawer.drawString(String.valueOf(-y_max / 2), 15, (int)((h * 3 / 4) - 5));
        //draw x scale
        boolean keep_drawing = true;
        double x_string_position = 10;
        double x_string_value = 0;
        while(keep_drawing){
            drawer.drawString(String.format("%.1f",x_string_value), (int)x_string_position, h/2);
            x_string_position += (w-15)/10;
            x_string_value += 0.1;
            keep_drawing = x_string_value < 1;
        }
        
    }
    
    public void graph_plot(double x, double y){
        int x_at_0 = 10;    //set the (0,0) point
        int y_at_0 = h / 2;
        int plot_x = x_at_0 + (int)(x * (w-15));
        int plot_y = y_at_0 - (int)(y / y_max * ((h - 20) / 2));
        //draw value on y-axis
        drawer.drawLine(plot_x, plot_y, plot_x_previous, plot_y_previous);
        plot_x_previous = plot_x;
        plot_y_previous = plot_y;
        
    }
    
    public void draw_min_max(){
        drawer.setColor(Color.blue);
        drawer.fillOval(7 + (int)(x_max_1st * (w-15)), h / 2 - 2 - (int)(y_max_1st / y_max * ((h - 20) / 2)), 5, 5);
        drawer.fillOval(7 + (int)(x_min_1st * (w-15)), h / 2 - 2 - (int)(y_min_1st / y_max * ((h - 20) / 2)), 5, 5);
        if(x_max_1st < 0.5){
            drawer.drawString(String.format("Maximum point(%.2f, %.2f)", x_max_1st, y_max_1st),
                                           7 + (int)(x_max_1st * (w-15)),
                                           h / 2 - (int)(y_max_1st / y_max * ((h - 20) / 2)));
        }
        if(x_min_1st < 0.5){
            drawer.drawString(String.format("Minimum point(%.2f, %.2f)", x_min_1st, y_min_1st),
                                           7 + (int)(x_min_1st * (w-15)),
                                           h / 2 - 2 - (int)(y_min_1st / y_max * ((h - 20) / 2)));
        }
        if(x_max_1st > 0.5){
            drawer.drawString(String.format("Maximum point(%.2f, %.2f)", x_max_1st, y_max_1st),
                                           -150 + (int)(x_max_1st * (w-15)),
                                           h / 2 - (int)(y_max_1st / y_max * ((h - 20) / 2)));
        }
        if(x_min_1st > 0.5){
            drawer.drawString(String.format("Minimum point(%.2f, %.2f)", x_min_1st, y_min_1st),
                                           -150 + (int)(x_min_1st * (w-15)),
                                           h / 2 - 2 - (int)(y_min_1st / y_max * ((h - 20) / 2)));
        }
    }
    
    public void graph_plot_g1t(){ //get value from gui -> initial graph -> plot graph
        double a1 = Double.parseDouble(tf_a1.getText());
        double f1 = Double.parseDouble(tf_f1.getText());
        y_max = a1;
        graph_initialize();
        for(double t = 0; t < 1; t += 0.0001){
            double g1t = a1 * Math.sin(2 * Math.PI * f1 * t);
            graph_plot(t, g1t);
            if(y_max_1st < g1t){
                    y_max_1st = g1t;
                    x_max_1st = t;
            }
            if(y_min_1st > g1t){
                    y_min_1st = g1t;
                    x_min_1st = t;
            }
        }
        draw_min_max();
    }
    
    public void graph_plot_g2t(){
        double a2 = Double.parseDouble(tf_a2.getText());
        double f2 = Double.parseDouble(tf_f2.getText());
        y_max = a2;
        graph_initialize();
        for(double t = 0; t < 1; t += 0.0001){
            double g2t = a2 * Math.sin(2 * Math.PI * f2 * t);
            graph_plot(t, g2t);
            if(y_max_1st < g2t){
                    y_max_1st = g2t;
                    x_max_1st = t;
            }
            if(y_min_1st > g2t){
                    y_min_1st = g2t;
                    x_min_1st = t;
            }
        }
        draw_min_max();
    }
    
    public void graph_plot_gt(){
        double a1 = Double.parseDouble(tf_a1.getText());
        double f1 = Double.parseDouble(tf_f1.getText());
        double a2 = Double.parseDouble(tf_a2.getText());
        double f2 = Double.parseDouble(tf_f2.getText());
        y_max = find_y_max(a1, a2);
        graph_initialize();
        for(double t = 0; t < 1; t += 0.0001){
            double g1t = a1 * Math.sin(2 * Math.PI * f1 * t);
            double g2t = a2 * Math.sin(2 * Math.PI * f2 * t);
            graph_plot(t, result(g1t, g2t));
            if(y_max_1st < result(g1t, g2t)){
                    y_max_1st = result(g1t, g2t);
                    x_max_1st = t;
            }
            if(y_min_1st > result(g1t, g2t)){
                    y_min_1st = result(g1t, g2t);
                    x_min_1st = t;
            }
        }
        draw_min_max();
    }
    
    public double result(double a, double b){
        double c = 0;
        String chk = (String)cb_operation.getSelectedItem();
        switch(chk){
            case "+" -> c = a + b;
            case "-" -> c = a - b;
            case "*" -> c = a * b;
            case "/" -> c = a / b;
        }
        return c;
    }
    
    public double find_y_max(double a, double b){
        double c = a >= b ? a : b;
        double d = 0;
        String chk = (String)cb_operation.getSelectedItem();
        switch(chk){
            case "+" -> d = result(a, b) >= c ? result(a, b) : c;
            case "-" -> d = a + b >= c ? a + b : c;
            case "*" -> d = result(a, b) >= c ? result(a, b) : c;
            case "/" -> d = result(a, b) >= c ? result(a, b) : c;
        }
        return d;
    }
    
    private void button_gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gtActionPerformed
        graph_plot_gt();
    }//GEN-LAST:event_button_gtActionPerformed

    private void button_g2tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_g2tActionPerformed
        graph_plot_g2t();
    }//GEN-LAST:event_button_g2tActionPerformed

    private void button_g1tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_g1tActionPerformed
        graph_plot_g1t();
    }//GEN-LAST:event_button_g1tActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(for_loop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(for_loop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(for_loop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(for_loop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new for_loop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_g1t;
    private javax.swing.JButton button_g2t;
    private javax.swing.JButton button_gt;
    private javax.swing.JComboBox<String> cb_operation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_graph;
    private javax.swing.JTextField tf_a1;
    private javax.swing.JTextField tf_a2;
    private javax.swing.JTextField tf_f1;
    private javax.swing.JTextField tf_f2;
    // End of variables declaration//GEN-END:variables
}
