
import java.util.Arrays;

/*
 * /*Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template*/
 



/**
 * @date 12/1/2022
 * @author Teng Ting Li
 */
public class matrix_gui extends javax.swing.JFrame {

    /**
     * Creates new form matrix_gui
     */
    public matrix_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_box_a11 = new javax.swing.JTextField();
        txt_box_a12 = new javax.swing.JTextField();
        txt_box_a13 = new javax.swing.JTextField();
        txt_box_a14 = new javax.swing.JTextField();
        txt_box_a21 = new javax.swing.JTextField();
        txt_box_a31 = new javax.swing.JTextField();
        txt_box_a41 = new javax.swing.JTextField();
        txt_box_a22 = new javax.swing.JTextField();
        txt_box_a23 = new javax.swing.JTextField();
        txt_box_a24 = new javax.swing.JTextField();
        txt_box_a32 = new javax.swing.JTextField();
        txt_box_a33 = new javax.swing.JTextField();
        txt_box_a34 = new javax.swing.JTextField();
        txt_box_a42 = new javax.swing.JTextField();
        txt_box_a43 = new javax.swing.JTextField();
        txt_box_a44 = new javax.swing.JTextField();
        txt_box_b21 = new javax.swing.JTextField();
        txt_box_b44 = new javax.swing.JTextField();
        txt_box_b31 = new javax.swing.JTextField();
        txt_box_b41 = new javax.swing.JTextField();
        txt_box_b22 = new javax.swing.JTextField();
        txt_box_b23 = new javax.swing.JTextField();
        txt_box_b24 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_box_b32 = new javax.swing.JTextField();
        txt_box_b11 = new javax.swing.JTextField();
        txt_box_b33 = new javax.swing.JTextField();
        txt_box_b12 = new javax.swing.JTextField();
        txt_box_b34 = new javax.swing.JTextField();
        txt_box_b13 = new javax.swing.JTextField();
        txt_box_b42 = new javax.swing.JTextField();
        txt_box_b14 = new javax.swing.JTextField();
        txt_box_b43 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        main_output = new javax.swing.JTextArea();
        button_inverse_1 = new javax.swing.JButton();
        cb_x = new javax.swing.JComboBox<>();
        button_display = new javax.swing.JButton();
        button_power = new javax.swing.JButton();
        tf_power = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("MATRIX GUI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Matrix A");

        txt_box_a11.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a11.setText("-1");

        txt_box_a12.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a12.setText("1");

        txt_box_a13.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a13.setText("1");

        txt_box_a14.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a14.setText("1");

        txt_box_a21.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a21.setText("0");

        txt_box_a31.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a31.setText("5");

        txt_box_a41.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a41.setText("1");

        txt_box_a22.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a22.setText("-4");
        txt_box_a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_box_a22ActionPerformed(evt);
            }
        });

        txt_box_a23.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a23.setText("4");

        txt_box_a24.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a24.setText("1");

        txt_box_a32.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a32.setText("1");

        txt_box_a33.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a33.setText("1");

        txt_box_a34.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a34.setText("1");
        txt_box_a34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_box_a34ActionPerformed(evt);
            }
        });

        txt_box_a42.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a42.setText("4");

        txt_box_a43.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a43.setText("1");

        txt_box_a44.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_a44.setText("1");

        txt_box_b21.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b21.setText("-4");

        txt_box_b44.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b44.setText("1");

        txt_box_b31.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b31.setText("1");

        txt_box_b41.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b41.setText("1");

        txt_box_b22.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b22.setText("3");

        txt_box_b23.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b23.setText("1");

        txt_box_b24.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b24.setText("-1");
        txt_box_b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_box_b24ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Matrix B");

        txt_box_b32.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b32.setText("1");

        txt_box_b11.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b11.setText("2");

        txt_box_b33.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b33.setText("5");

        txt_box_b12.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b12.setText("1");

        txt_box_b34.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b34.setText("1");

        txt_box_b13.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b13.setText("7");

        txt_box_b42.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b42.setText("0");

        txt_box_b14.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b14.setText("1");

        txt_box_b43.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txt_box_b43.setText("1");

        main_output.setColumns(20);
        main_output.setRows(5);
        jScrollPane1.setViewportView(main_output);

        button_inverse_1.setText("Inverse");
        button_inverse_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_inverse_1ActionPerformed(evt);
            }
        });

        cb_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));

        button_display.setText("Display");
        button_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_displayActionPerformed(evt);
            }
        });

        button_power.setText("Power");
        button_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_powerActionPerformed(evt);
            }
        });

        tf_power.setText("2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_box_a41, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_a42, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_a43, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_a44, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_box_a31, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_box_a32, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_box_a21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_box_a22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_box_a23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_box_a24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_box_a33, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_box_a34, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_box_a11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_a12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_a13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_a14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_box_b11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_b12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_b13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_box_b14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_box_b31, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b32, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_box_b21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_box_b23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_box_b33, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b34, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(button_power)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_box_b41, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b42, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b43, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_box_b44, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(tf_power, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(149, 149, 149))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_display)
                                .addGap(48, 48, 48)
                                .addComponent(button_inverse_1))
                            .addComponent(cb_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_b21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_b31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_b41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_b44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_a11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_a21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_a31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_box_a41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_box_a44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(cb_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_display)
                    .addComponent(button_inverse_1)
                    .addComponent(button_power)
                    .addComponent(tf_power, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void display(double[][] a, String s){
        main_output.append(s + "\n");
        for(int i = 0; i < a.length; i ++){
            for(int j = 0; j < a[i].length; j ++){
                String str = String.format("%.2f", a[i][j]);
                main_output.append(str);
                main_output.append(" ");
            }
            main_output.append("\n");
        }
    }
    
    private double determinant(double[][] matrix) {
        if (matrix.length != matrix[0].length)
            throw new IllegalStateException("invalid dimensions");

        if (matrix.length == 2)
            return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0];

        double det = 0;
        for (int i = 0; i < matrix[0].length; i++){
            det += Math.pow(-1, i) * matrix[0][i] * determinant(submatrix(matrix, 0, i));
        }
            return det;
    }

     private double[][] inverse(double[][] matrix) {
        double[][] inverse = new double[matrix.length][matrix.length];

        // minors and cofactors
        for (int i = 0; i < matrix.length; i++){
            for (int j = 0; j < matrix[i].length; j++){
                inverse[i][j] = Math.pow(-1, i + j) * determinant(submatrix(matrix, i, j));
            }
        }
        // adjugate and determinant
        double det = 1.0 / determinant(matrix);
        for (int i = 0; i < inverse.length; i++) {
            for (int j = 0; j <= i; j++) {
                double temp = inverse[i][j];
                inverse[i][j] = inverse[j][i] * det;
                inverse[j][i] = temp * det;
            }
        }

        return inverse;
    }

    private double[][] submatrix(double[][] matrix, int row, int column) {
        double[][] submatrix = new double[matrix.length - 1][matrix.length - 1];

        for (int i = 0; i < matrix.length; i++)
            for (int j = 0; i != row && j < matrix[i].length; j++)
                if (j != column)
                    submatrix[i < row ? i : i - 1][j < column ? j : j - 1] = matrix[i][j];
        return submatrix;
    }

    private double[][] multiply2(double[][] a, double[][] b) {
        if (a[0].length != b.length)
            throw new IllegalStateException("invalid dimensions");

        double[][] matrix = new double[a.length][b[0].length];
        for (int i = 0; i < a.length; i++) {
            for (int j = 0; j < b[0].length; j++) {
                double sum = 0;
                for (int k = 0; k < a[i].length; k++)
                    sum += a[i][k] * b[k][j];
                matrix[i][j] = sum;
            }
        }

        return matrix;
    }

    private double[][] rref(double[][] matrix) {
        double[][] rref = new double[matrix.length][];
        for (int i = 0; i < matrix.length; i++)
            rref[i] = Arrays.copyOf(matrix[i], matrix[i].length);

        int r = 0;
        for (int c = 0; c < rref[0].length && r < rref.length; c++) {
            int j = r;
            for (int i = r + 1; i < rref.length; i++)
                if (Math.abs(rref[i][c]) > Math.abs(rref[j][c]))
                    j = i;
            if (Math.abs(rref[j][c]) < 0.00001)
                continue;

            double[] temp = rref[j];
            rref[j] = rref[r];
            rref[r] = temp;

            double s = 1.0 / rref[r][c];
            for (j = 0; j < rref[0].length; j++)
                rref[r][j] *= s;
            for (int i = 0; i < rref.length; i++) {
                if (i != r) {
                    double t = rref[i][c];
                    for (j = 0; j < rref[0].length; j++)
                        rref[i][j] -= t * rref[r][j];
                }
            }
            r++;
        }

        return rref;
    }

    private double[][] transpose(double[][] matrix) {
        double[][] transpose = new double[matrix[0].length][matrix.length];

        for (int i = 0; i < matrix.length; i++)
            for (int j = 0; j < matrix[i].length; j++)
                transpose[j][i] = matrix[i][j];
        return transpose;
    }

    private double [][]powerMatrix(double [][]A, double n){
        double [][]result=A;
    
        for(int i=1;i<n;i++){
        result = multiply2(result,A);}
    
    return result;
    }
    
    private void button_inverse_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_inverse_1ActionPerformed
        //<editor-fold defaultstate="collapsed" desc="for initialize A">
        double a11 = Double.parseDouble(txt_box_a11.getText());
        double a12 = Double.parseDouble(txt_box_a12.getText());
        double a13 = Double.parseDouble(txt_box_a13.getText());
        double a14 = Double.parseDouble(txt_box_a14.getText());
        double a21 = Double.parseDouble(txt_box_a21.getText());
        double a22 = Double.parseDouble(txt_box_a22.getText());
        double a23 = Double.parseDouble(txt_box_a23.getText());
        double a24 = Double.parseDouble(txt_box_a24.getText());
        double a31 = Double.parseDouble(txt_box_a31.getText());
        double a32 = Double.parseDouble(txt_box_a32.getText());
        double a33 = Double.parseDouble(txt_box_a33.getText());
        double a34 = Double.parseDouble(txt_box_a34.getText());
        double a41 = Double.parseDouble(txt_box_a41.getText());
        double a42 = Double.parseDouble(txt_box_a42.getText());
        double a43 = Double.parseDouble(txt_box_a43.getText());
        double a44 = Double.parseDouble(txt_box_a44.getText());
        double a[][] = {{a11,a12,a13,a14},
                               {a21,a22,a23,a24},
                               {a31,a32,a33,a34},
                               {a41,a42,a43,a44}};//</editor-fold>
        //<editor-fold defaultstate="collapsed" desc="for initialize B">
        double b11 = Double.parseDouble(txt_box_b11.getText());
        double b12 = Double.parseDouble(txt_box_b12.getText());
        double b13 = Double.parseDouble(txt_box_b13.getText());
        double b14 = Double.parseDouble(txt_box_b14.getText());
        double b21 = Double.parseDouble(txt_box_b21.getText());
        double b22 = Double.parseDouble(txt_box_b22.getText());
        double b23 = Double.parseDouble(txt_box_b23.getText());
        double b24 = Double.parseDouble(txt_box_b24.getText());
        double b31 = Double.parseDouble(txt_box_b31.getText());
        double b32 = Double.parseDouble(txt_box_b32.getText());
        double b33 = Double.parseDouble(txt_box_b33.getText());
        double b34 = Double.parseDouble(txt_box_b34.getText());
        double b41 = Double.parseDouble(txt_box_b41.getText());
        double b42 = Double.parseDouble(txt_box_b42.getText());
        double b43 = Double.parseDouble(txt_box_b43.getText());
        double b44 = Double.parseDouble(txt_box_b44.getText());
        double b[][] = {{b11,b12,b13,b14},
                               {b21,b22,b23,b24},
                               {b31,b32,b33,b34},
                               {b41,b42,b43,b44}}; //</editor-fold>
        String check_cb_x1 = (String)cb_x.getSelectedItem();
        switch(check_cb_x1){
            case "A" -> display(inverse(a),"mat A-1");
            case "B" -> display(inverse(b),"mat B-1");
        }
        
    }//GEN-LAST:event_button_inverse_1ActionPerformed

    private void button_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_displayActionPerformed
       //<editor-fold defaultstate="collapsed" desc="for initialize A">
        double a11 = Double.parseDouble(txt_box_a11.getText());
        double a12 = Double.parseDouble(txt_box_a12.getText());
        double a13 = Double.parseDouble(txt_box_a13.getText());
        double a14 = Double.parseDouble(txt_box_a14.getText());
        double a21 = Double.parseDouble(txt_box_a21.getText());
        double a22 = Double.parseDouble(txt_box_a22.getText());
        double a23 = Double.parseDouble(txt_box_a23.getText());
        double a24 = Double.parseDouble(txt_box_a24.getText());
        double a31 = Double.parseDouble(txt_box_a31.getText());
        double a32 = Double.parseDouble(txt_box_a32.getText());
        double a33 = Double.parseDouble(txt_box_a33.getText());
        double a34 = Double.parseDouble(txt_box_a34.getText());
        double a41 = Double.parseDouble(txt_box_a41.getText());
        double a42 = Double.parseDouble(txt_box_a42.getText());
        double a43 = Double.parseDouble(txt_box_a43.getText());
        double a44 = Double.parseDouble(txt_box_a44.getText());
        double a[][] = {{a11,a12,a13,a14},
                               {a21,a22,a23,a24},
                               {a31,a32,a33,a34},
                               {a41,a42,a43,a44}};//</editor-fold>
       //<editor-fold defaultstate="collapsed" desc="for initialize B">
        double b11 = Double.parseDouble(txt_box_b11.getText());
        double b12 = Double.parseDouble(txt_box_b12.getText());
        double b13 = Double.parseDouble(txt_box_b13.getText());
        double b14 = Double.parseDouble(txt_box_b14.getText());
        double b21 = Double.parseDouble(txt_box_b21.getText());
        double b22 = Double.parseDouble(txt_box_b22.getText());
        double b23 = Double.parseDouble(txt_box_b23.getText());
        double b24 = Double.parseDouble(txt_box_b24.getText());
        double b31 = Double.parseDouble(txt_box_b31.getText());
        double b32 = Double.parseDouble(txt_box_b32.getText());
        double b33 = Double.parseDouble(txt_box_b33.getText());
        double b34 = Double.parseDouble(txt_box_b34.getText());
        double b41 = Double.parseDouble(txt_box_b41.getText());
        double b42 = Double.parseDouble(txt_box_b42.getText());
        double b43 = Double.parseDouble(txt_box_b43.getText());
        double b44 = Double.parseDouble(txt_box_b44.getText());
        double b[][] = {{b11,b12,b13,b14},
                               {b21,b22,b23,b24},
                               {b31,b32,b33,b34},
                               {b41,b42,b43,b44}}; //</editor-fold>
        String check_cb_x = (String)cb_x.getSelectedItem();
        switch(check_cb_x){
            case "A" -> display(a,"mat A");
            case "B" -> display(b,"mat B");
    }//GEN-LAST:event_button_displayActionPerformed
    }
    
    private void txt_box_a22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_box_a22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_box_a22ActionPerformed

    private void txt_box_b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_box_b24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_box_b24ActionPerformed

    private void txt_box_a34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_box_a34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_box_a34ActionPerformed

    private void button_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_powerActionPerformed
       //<editor-fold defaultstate="collapsed" desc="for initialize A">
        double a11 = Double.parseDouble(txt_box_a11.getText());
        double a12 = Double.parseDouble(txt_box_a12.getText());
        double a13 = Double.parseDouble(txt_box_a13.getText());
        double a14 = Double.parseDouble(txt_box_a14.getText());
        double a21 = Double.parseDouble(txt_box_a21.getText());
        double a22 = Double.parseDouble(txt_box_a22.getText());
        double a23 = Double.parseDouble(txt_box_a23.getText());
        double a24 = Double.parseDouble(txt_box_a24.getText());
        double a31 = Double.parseDouble(txt_box_a31.getText());
        double a32 = Double.parseDouble(txt_box_a32.getText());
        double a33 = Double.parseDouble(txt_box_a33.getText());
        double a34 = Double.parseDouble(txt_box_a34.getText());
        double a41 = Double.parseDouble(txt_box_a41.getText());
        double a42 = Double.parseDouble(txt_box_a42.getText());
        double a43 = Double.parseDouble(txt_box_a43.getText());
        double a44 = Double.parseDouble(txt_box_a44.getText());
        double a[][] = {{a11,a12,a13,a14},
                               {a21,a22,a23,a24},
                               {a31,a32,a33,a34},
                               {a41,a42,a43,a44}};//</editor-fold>
       //<editor-fold defaultstate="collapsed" desc="for initialize B">
        double b11 = Double.parseDouble(txt_box_b11.getText());
        double b12 = Double.parseDouble(txt_box_b12.getText());
        double b13 = Double.parseDouble(txt_box_b13.getText());
        double b14 = Double.parseDouble(txt_box_b14.getText());
        double b21 = Double.parseDouble(txt_box_b21.getText());
        double b22 = Double.parseDouble(txt_box_b22.getText());
        double b23 = Double.parseDouble(txt_box_b23.getText());
        double b24 = Double.parseDouble(txt_box_b24.getText());
        double b31 = Double.parseDouble(txt_box_b31.getText());
        double b32 = Double.parseDouble(txt_box_b32.getText());
        double b33 = Double.parseDouble(txt_box_b33.getText());
        double b34 = Double.parseDouble(txt_box_b34.getText());
        double b41 = Double.parseDouble(txt_box_b41.getText());
        double b42 = Double.parseDouble(txt_box_b42.getText());
        double b43 = Double.parseDouble(txt_box_b43.getText());
        double b44 = Double.parseDouble(txt_box_b44.getText());
        double b[][] = {{b11,b12,b13,b14},
                               {b21,b22,b23,b24},
                               {b31,b32,b33,b34},
                               {b41,b42,b43,b44}}; //</editor-fold>
        int power = Integer.parseInt(tf_power.getText());
        String check_cb_x = (String)cb_x.getSelectedItem();
        switch(check_cb_x){
            case "A" -> display(powerMatrix(a, power),"mat A^" + power);
            case "B" -> display(powerMatrix(b, power),"mat B^" + power);
        }
    }//GEN-LAST:event_button_powerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matrix_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matrix_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matrix_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matrix_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matrix_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_display;
    private javax.swing.JButton button_inverse_1;
    private javax.swing.JButton button_power;
    private javax.swing.JComboBox<String> cb_x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea main_output;
    private javax.swing.JTextField tf_power;
    private javax.swing.JTextField txt_box_a11;
    private javax.swing.JTextField txt_box_a12;
    private javax.swing.JTextField txt_box_a13;
    private javax.swing.JTextField txt_box_a14;
    private javax.swing.JTextField txt_box_a21;
    private javax.swing.JTextField txt_box_a22;
    private javax.swing.JTextField txt_box_a23;
    private javax.swing.JTextField txt_box_a24;
    private javax.swing.JTextField txt_box_a31;
    private javax.swing.JTextField txt_box_a32;
    private javax.swing.JTextField txt_box_a33;
    private javax.swing.JTextField txt_box_a34;
    private javax.swing.JTextField txt_box_a41;
    private javax.swing.JTextField txt_box_a42;
    private javax.swing.JTextField txt_box_a43;
    private javax.swing.JTextField txt_box_a44;
    private javax.swing.JTextField txt_box_b11;
    private javax.swing.JTextField txt_box_b12;
    private javax.swing.JTextField txt_box_b13;
    private javax.swing.JTextField txt_box_b14;
    private javax.swing.JTextField txt_box_b21;
    private javax.swing.JTextField txt_box_b22;
    private javax.swing.JTextField txt_box_b23;
    private javax.swing.JTextField txt_box_b24;
    private javax.swing.JTextField txt_box_b31;
    private javax.swing.JTextField txt_box_b32;
    private javax.swing.JTextField txt_box_b33;
    private javax.swing.JTextField txt_box_b34;
    private javax.swing.JTextField txt_box_b41;
    private javax.swing.JTextField txt_box_b42;
    private javax.swing.JTextField txt_box_b43;
    private javax.swing.JTextField txt_box_b44;
    // End of variables declaration//GEN-END:variables
}
